name: Job Dependencies Workflow
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Building application
        run: echo "Building application..." && sleep 5
      - name: Build complete
        run: echo "Build finished successfully!"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Running tests
        run: echo "Running tests..." && sleep 3
      - name: Tests complete
        run: echo "All tests passed successfully!"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploying application
        run: echo "Deploying application..." && sleep 2
      - name: Deployment complete
        run: echo "Application deployed successfully!"
