name: Multi-Platform Testing

on:
  pull_request:
    branches: [ main ]

jobs:
  ubuntu-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create file
        run: |
          echo "Running on Ubuntu" > info.txt
          cat info.txt

  windows-job:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: OS info
        run: systeminfo
      - name: Create file
        run: |
          echo "Running on Windows" > info.txt
          type info.txt

  macos-job:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: OS info
        run: uname -a
      - name: Create file
        run: |
          echo "Running on macOS" > info.txt
          cat info.txt
